CREATE DATABASE PROYECTO; 
		
/*CREACIÓN DE TABLAS*/
CREATE TABLE PRODUCTO (ID_PRODUCTO INT IDENTITY PRIMARY KEY,
					   NOMBRE VARCHAR(50) NOT NULL,
					   NOMBRE_A_MOSTRAR VARCHAR(25) NOT NULL,
					   UNIDAD_DE_MEDIDA VARCHAR(20),
					   TIPO VARCHAR(20) NOT NULL,
					   SUBTIPO VARCHAR(20),
					   PRECIO DECIMAL(6, 2) NOT NULL,
					   PRECIO_COSTE DECIMAL(6, 2),
		/**CALCULADO*/ PRECIO_FINAL DECIMAL(6, 2),
		/**CALCULADO*/ MARGEN DECIMAL(6, 2),
		/**CALCULADO*/ BENEFICIO DECIMAL(6, 2),
					   IMPUESTO DECIMAL(6, 2) DEFAULT 21, 
					   IMPUESTO2 DECIMAL(6, 2) DEFAULT 0, 
					   EXISTENCIAS INT DEFAULT 0,
					   FAVORITO INT DEFAULT 0,
					   IMAGEN VARCHAR(100));
					  
CREATE TABLE TRABAJADOR(DNI VARCHAR(9) PRIMARY KEY, 
						NOMBRE VARCHAR(30) NOT NULL,
						NOMBRE_USUARIO VARCHAR(10) NOT NULL,
						FECHA_NACIMIENTO DATE,
						CLAVE VARCHAR(9) NOT NULL);
					 
CREATE TABLE PEDIDO(ID_PEDIDO INT IDENTITY  PRIMARY KEY, 
					DNI VARCHAR(9) FOREIGN KEY REFERENCES TRABAJADOR(DNI),
					FECHA DATE, 
					IMPORTE DECIMAL(6, 2));
					
					
CREATE TABLE TIENE_PROD_PED(ID_PRODUCTO INT NOT NULL, 
							ID_PEDIDO INT NOT NULL, 
							CANTIDAD INT, 
							PRECIO_ACTUAL DECIMAL(6, 2), 
							PRIMARY KEY(ID_PRODUCTO, ID_PEDIDO)); 


